<?php
if (!defined('ABSPATH')) {
    exit;
}

class ASWC_Ajax {
    public function __construct() {
        // Ensure action names match JS ('get_algeria_cities')
        add_action('wp_ajax_get_algeria_cities', array($this, 'get_algeria_cities_ajax'));
        add_action('wp_ajax_nopriv_get_algeria_cities', array($this, 'get_algeria_cities_ajax'));
    }

    public function get_algeria_cities_ajax() {
        // Ensure nonce check matches the name used in wp_localize_script ('aswc-nonce')
        check_ajax_referer('aswc-nonce', 'nonce'); 

        // Ensure parameter name matches JS ('wilaya_id')
        if (isset($_POST['wilaya_id'])) {
            $wilaya_id = sanitize_text_field($_POST['wilaya_id']);
            $cities = $this->get_cities_for_wilaya($wilaya_id); // Implement this method
            
            if (!empty($cities)) {
                wp_send_json_success($cities);
            } else {
                wp_send_json_error('No cities found for this state.');
            }
        } else {
            wp_send_json_error('State ID not provided.');
        }
        wp_die();
    }

    // Example function - replace with your actual city data retrieval
    private function get_cities_for_wilaya($wilaya_id) {
        // Your logic to get cities based on $wilaya_id
        // Example:
        $all_cities = array(
            '1' => array(
                __('Adrar', 'algeria-states-wc'),
                __('Akabli', 'algeria-states-wc'),
                __('Aoulef', 'algeria-states-wc'),
                __('Bouda', 'algeria-states-wc'),
                __('Fenoughil', 'algeria-states-wc'),
                __('In Zghmir', 'algeria-states-wc'),
                __('Ouled Ahmed Timmi', 'algeria-states-wc'),
                __('Reggane', 'algeria-states-wc'),
                __('Sali', 'algeria-states-wc'),
                __('Sebaa', 'algeria-states-wc'),
                __('Tamantit', 'algeria-states-wc'),
                __('Tamest', 'algeria-states-wc'),
                __('Timekten', 'algeria-states-wc'),
                __('Tit', 'algeria-states-wc'),
                __('Tsabit', 'algeria-states-wc'),
                __('Zaouiet Kounta', 'algeria-states-wc'),
            ),
            '2' => array(
                __('Abou El Hassane', 'algeria-states-wc'),
                __('Ain Merane', 'algeria-states-wc'),
                __('Benairia', 'algeria-states-wc'),
                __('Beni  Bouattab', 'algeria-states-wc'),
                __('Beni Haoua', 'algeria-states-wc'),
                __('Beni Rached', 'algeria-states-wc'),
                __('Boukadir', 'algeria-states-wc'),
                __('Bouzeghaia', 'algeria-states-wc'),
                __('Breira', 'algeria-states-wc'),
                __('Chettia', 'algeria-states-wc'),
                __('Chlef', 'algeria-states-wc'),
                __('Dahra', 'algeria-states-wc'),
                __('El Hadjadj', 'algeria-states-wc'),
                __('El Karimia', 'algeria-states-wc'),
                __('El Marsa', 'algeria-states-wc'),
                __('Harchoun', 'algeria-states-wc'),
                __('Herenfa', 'algeria-states-wc'),
                __('Labiod Medjadja', 'algeria-states-wc'),
                __('Moussadek', 'algeria-states-wc'),
                __('Oued Fodda', 'algeria-states-wc'),
                __('Oued Goussine', 'algeria-states-wc'),
                __('Oued Sly', 'algeria-states-wc'),
                __('Ouled Abbes', 'algeria-states-wc'),
                __('Ouled Ben Abdelkader', 'algeria-states-wc'),
                __('Ouled Fares', 'algeria-states-wc'),
                __('Oum Drou', 'algeria-states-wc'),
                __('Sendjas', 'algeria-states-wc'),
                __('Sidi Abderrahmane', 'algeria-states-wc'),
                __('Sidi Akkacha', 'algeria-states-wc'),
                __('Sobha', 'algeria-states-wc'),
                __('Tadjena', 'algeria-states-wc'),
                __('Talassa', 'algeria-states-wc'),
                __('Taougrit', 'algeria-states-wc'),
                __('Tenes', 'algeria-states-wc'),
                __('Zeboudja', 'algeria-states-wc'),
            ),
            '3' => array(
                __('Aflou', 'algeria-states-wc'),
                __('Ain Madhi', 'algeria-states-wc'),
                __('Ain Sidi Ali', 'algeria-states-wc'),
                __('Benacer Benchohra', 'algeria-states-wc'),
                __('Brida', 'algeria-states-wc'),
                __('El Assafia', 'algeria-states-wc'),
                __('El Beidha', 'algeria-states-wc'),
                __('El Ghicha', 'algeria-states-wc'),
                __('El Haouaita', 'algeria-states-wc'),
                __('Gueltat Sidi Saad', 'algeria-states-wc'),
                __('Hadj Mechri', 'algeria-states-wc'),
                __('Hassi Delaa', 'algeria-states-wc'),
                __('Hassi Rmel', 'algeria-states-wc'),
                __('Kheneg', 'algeria-states-wc'),
                __('Ksar El Hirane', 'algeria-states-wc'),
                __('Laghouat', 'algeria-states-wc'),
                __('Oued Mzi', 'algeria-states-wc'),
                __('Oued Morra', 'algeria-states-wc'),
                __('Sebgag', 'algeria-states-wc'),
                __('Sidi Bouzid', 'algeria-states-wc'),
                __('Sidi Makhlouf', 'algeria-states-wc'),
                __('Tadjemout', 'algeria-states-wc'),
                __('Tadjrouna', 'algeria-states-wc'),
                __('Taouiala', 'algeria-states-wc'),
            ),
            '4' => array(
                __('Ain Babouche', 'algeria-states-wc'),
                __('Ain Beida', 'algeria-states-wc'),
                __('Ain Diss', 'algeria-states-wc'),
                __('Ain Fekroun', 'algeria-states-wc'),
                __('Ain Kercha', 'algeria-states-wc'),
                __('Ain Mlila', 'algeria-states-wc'),
                __('Ain Zitoun', 'algeria-states-wc'),
                __('Behir Chergui', 'algeria-states-wc'),
                __('Berriche', 'algeria-states-wc'),
                __('Bir Chouhada', 'algeria-states-wc'),
                __('Dhalaa', 'algeria-states-wc'),
                __('El Amiria', 'algeria-states-wc'),
                __('El Belala', 'algeria-states-wc'),
                __('El Djazia', 'algeria-states-wc'),
                __('El Fedjoudj Boughrara Sa', 'algeria-states-wc'),
                __('El Harmilia', 'algeria-states-wc'),
                __('Fkirina', 'algeria-states-wc'),
                __('Hanchir Toumghani', 'algeria-states-wc'),
                __('Ksar Sbahi', 'algeria-states-wc'),
                __('Meskiana', 'algeria-states-wc'),
                __('Oued Nini', 'algeria-states-wc'),
                __('Ouled Gacem', 'algeria-states-wc'),
                __('Ouled Hamla', 'algeria-states-wc'),
                __('Ouled Zouai', 'algeria-states-wc'),
                __('Oum El Bouaghi', 'algeria-states-wc'),
                __('Rahia', 'algeria-states-wc'),
                __('Sigus', 'algeria-states-wc'),
                __('Souk Naamane', 'algeria-states-wc'),
                __('Zorg', 'algeria-states-wc'),
            ),
            '5' => array(
                __('Ain Djasser', 'algeria-states-wc'),
                __('Ain Touta', 'algeria-states-wc'),
                __('Ain Yagout', 'algeria-states-wc'),
                __('Arris', 'algeria-states-wc'),
                __('Azil Abedelkader', 'algeria-states-wc'),
                __('Barika', 'algeria-states-wc'),
                __('Batna', 'algeria-states-wc'),
                __('Beni Foudhala El Hakania', 'algeria-states-wc'),
                __('Bitam', 'algeria-states-wc'),
                __('Boulhilat', 'algeria-states-wc'),
                __('Boumagueur', 'algeria-states-wc'),
                __('Boumia', 'algeria-states-wc'),
                __('Bouzina', 'algeria-states-wc'),
                __('Chemora', 'algeria-states-wc'),
                __('Chir', 'algeria-states-wc'),
                __('Djerma', 'algeria-states-wc'),
                __('Djezzar', 'algeria-states-wc'),
                __('El Hassi', 'algeria-states-wc'),
                __('El Madher', 'algeria-states-wc'),
                __('Fesdis', 'algeria-states-wc'),
                __('Foum Toub', 'algeria-states-wc'),
                __('Ghassira', 'algeria-states-wc'),
                __('Gosbat', 'algeria-states-wc'),
                __('Guigba', 'algeria-states-wc'),
                __('Hidoussa', 'algeria-states-wc'),
                __('Ichemoul', 'algeria-states-wc'),
                __('Inoughissen', 'algeria-states-wc'),
                __('Kimmel', 'algeria-states-wc'),
                __('Ksar Bellezma', 'algeria-states-wc'),
                __('Larbaa', 'algeria-states-wc'),
                __('Lazrou', 'algeria-states-wc'),
                __('Lemcene', 'algeria-states-wc'),
                __('M Doukal', 'algeria-states-wc'),
                __('Maafa', 'algeria-states-wc'),
                __('Menaa', 'algeria-states-wc'),
                __('Merouana', 'algeria-states-wc'),
                __('N Gaous', 'algeria-states-wc'),
                __('Oued Chaaba', 'algeria-states-wc'),
                __('Oued El Ma', 'algeria-states-wc'),
                __('Oued Taga', 'algeria-states-wc'),
                __('Ouled Ammar', 'algeria-states-wc'),
                __('Ouled Aouf', 'algeria-states-wc'),
                __('Ouled Fadel', 'algeria-states-wc'),
                __('Ouled Sellem', 'algeria-states-wc'),
                __('Ouled Si Slimane', 'algeria-states-wc'),
                __('Ouyoun El Assafir', 'algeria-states-wc'),
                __('Rahbat', 'algeria-states-wc'),
                __('Ras El Aioun', 'algeria-states-wc'),
                __('Sefiane', 'algeria-states-wc'),
                __('Seggana', 'algeria-states-wc'),
                __('Seriana', 'algeria-states-wc'),
                __('T Kout', 'algeria-states-wc'),
                __('Talkhamt', 'algeria-states-wc'),
                __('Taxlent', 'algeria-states-wc'),
                __('Tazoult', 'algeria-states-wc'),
                __('Teniet El Abed', 'algeria-states-wc'),
                __('Tighanimine', 'algeria-states-wc'),
                __('Tigharghar', 'algeria-states-wc'),
                __('Tilatou', 'algeria-states-wc'),
                __('Timgad', 'algeria-states-wc'),
                __('Zanet El Beida', 'algeria-states-wc'),
            ),
            '6' => array(
                __('Adekar', 'algeria-states-wc'),
                __('Ait Rzine', 'algeria-states-wc'),
                __('Ait-Smail', 'algeria-states-wc'),
                __('Akbou', 'algeria-states-wc'),
                __('Akfadou', 'algeria-states-wc'),
                __('Amalou', 'algeria-states-wc'),
                __('Amizour', 'algeria-states-wc'),
                __('Aokas', 'algeria-states-wc'),
                __('Barbacha', 'algeria-states-wc'),
                __('Bejaia', 'algeria-states-wc'),
                __('Beni Djellil', 'algeria-states-wc'),
                __('Beni Ksila', 'algeria-states-wc'),
                __('Beni-Mallikeche', 'algeria-states-wc'),
                __('Benimaouche', 'algeria-states-wc'),
                __('Boudjellil', 'algeria-states-wc'),
                __('Bouhamza', 'algeria-states-wc'),
                __('Boukhelifa', 'algeria-states-wc'),
                __('Chellata', 'algeria-states-wc'),
                __('Chemini', 'algeria-states-wc'),
                __('Darguina', 'algeria-states-wc'),
                __('Dra El Caid', 'algeria-states-wc'),
                __('El Kseur', 'algeria-states-wc'),
                __('Fenaia Il Maten', 'algeria-states-wc'),
                __('Feraoun', 'algeria-states-wc'),
                __('Ighil-Ali', 'algeria-states-wc'),
                __('Ighram', 'algeria-states-wc'),
                __('Kendira', 'algeria-states-wc'),
                __('Kherrata', 'algeria-states-wc'),
                __('Leflaye', 'algeria-states-wc'),
                __('Mcisna', 'algeria-states-wc'),
                __('Melbou', 'algeria-states-wc'),
                __('Oued Ghir', 'algeria-states-wc'),
                __('Ouzellaguen', 'algeria-states-wc'),
                __('Seddouk', 'algeria-states-wc'),
                __('Sidi Ayad', 'algeria-states-wc'),
                __('Sidi-Aich', 'algeria-states-wc'),
                __('Smaoun', 'algeria-states-wc'),
                __('Souk El Tenine', 'algeria-states-wc'),
                __('Souk Oufella', 'algeria-states-wc'),
                __('Tala Hamza', 'algeria-states-wc'),
                __('Tamokra', 'algeria-states-wc'),
                __('Tamridjet', 'algeria-states-wc'),
                __('Taourit Ighil', 'algeria-states-wc'),
                __('Taskriout', 'algeria-states-wc'),
                __('Tazmalt', 'algeria-states-wc'),
                __('Tibane', 'algeria-states-wc'),
                __('Tichy', 'algeria-states-wc'),
                __('Tifra', 'algeria-states-wc'),
                __('Timezrit', 'algeria-states-wc'),
                __('Tinebdar', 'algeria-states-wc'),
                __('Tizi Nberber', 'algeria-states-wc'),
                __('Toudja', 'algeria-states-wc'),
            ),
            '7' => array(
                __('Ain Naga', 'algeria-states-wc'),
                __('Ain Zaatout', 'algeria-states-wc'),
                __('Biskra', 'algeria-states-wc'),
                __('Bordj Ben Azzouz', 'algeria-states-wc'),
                __('Bouchakroun', 'algeria-states-wc'),
                __('Branis', 'algeria-states-wc'),
                __('Chetma', 'algeria-states-wc'),
                __('Djemorah', 'algeria-states-wc'),
                __('El Feidh', 'algeria-states-wc'),
                __('El Ghrous', 'algeria-states-wc'),
                __('El Hadjab', 'algeria-states-wc'),
                __('El Haouch', 'algeria-states-wc'),
                __('El Kantara', 'algeria-states-wc'),
                __('El Outaya', 'algeria-states-wc'),
                __('Foughala', 'algeria-states-wc'),
                __('Khenguet Sidi Nadji', 'algeria-states-wc'),
                __('Lichana', 'algeria-states-wc'),
                __('Lioua', 'algeria-states-wc'),
                __('Mchouneche', 'algeria-states-wc'),
                __('Mlili', 'algeria-states-wc'),
                __('Mekhadma', 'algeria-states-wc'),
                __('Meziraa', 'algeria-states-wc'),
                __('Oumache', 'algeria-states-wc'),
                __('Ourlal', 'algeria-states-wc'),
                __('Sidi Okba', 'algeria-states-wc'),
                __('Tolga', 'algeria-states-wc'),
                __('Zeribet El Oued', 'algeria-states-wc'),
            ),
            '8' => array(
                __('Abadla', 'algeria-states-wc'),
                __('Bechar', 'algeria-states-wc'),
                __('Beni-Ounif', 'algeria-states-wc'),
                __('Boukais', 'algeria-states-wc'),
                __('Erg-Ferradj', 'algeria-states-wc'),
                __('Kenadsa', 'algeria-states-wc'),
                __('Lahmar', 'algeria-states-wc'),
                __('Machraa-Houari-Boumediene', 'algeria-states-wc'),
                __('Meridja', 'algeria-states-wc'),
                __('Mogheul', 'algeria-states-wc'),
                __('Tabelbala', 'algeria-states-wc'),
                __('Taghit', 'algeria-states-wc'),
            ),
            '9' => array(
                __('Ain Romana', 'algeria-states-wc'),
                __('Beni Mered', 'algeria-states-wc'),
                __('Beni-Tamou', 'algeria-states-wc'),
                __('Benkhelil', 'algeria-states-wc'),
                __('Blida', 'algeria-states-wc'),
                __('Bouarfa', 'algeria-states-wc'),
                __('Boufarik', 'algeria-states-wc'),
                __('Bougara', 'algeria-states-wc'),
                __('Bouinan', 'algeria-states-wc'),
                __('Chebli', 'algeria-states-wc'),
                __('Chiffa', 'algeria-states-wc'),
                __('Chrea', 'algeria-states-wc'),
                __('Djebabra', 'algeria-states-wc'),
                __('El-Affroun', 'algeria-states-wc'),
                __('Guerrouaou', 'algeria-states-wc'),
                __('Hammam Elouane', 'algeria-states-wc'),
                __('Larbaa', 'algeria-states-wc'),
                __('Meftah', 'algeria-states-wc'),
                __('Mouzaia', 'algeria-states-wc'),
                __('Oued  Djer', 'algeria-states-wc'),
                __('Oued El Alleug', 'algeria-states-wc'),
                __('Ouled Slama', 'algeria-states-wc'),
                __('Ouled Yaich', 'algeria-states-wc'),
                __('Souhane', 'algeria-states-wc'),
                __('Soumaa', 'algeria-states-wc'),
            ),
            '10' => array(
                __('Aghbalou', 'algeria-states-wc'),
                __('Ahl El Ksar', 'algeria-states-wc'),
                __('Ain El Hadjar', 'algeria-states-wc'),
                __('Ain Laloui', 'algeria-states-wc'),
                __('Ain Turk', 'algeria-states-wc'),
                __('Ain-Bessem', 'algeria-states-wc'),
                __('Ait Laaziz', 'algeria-states-wc'),
                __('Aomar', 'algeria-states-wc'),
                __('Ath Mansour', 'algeria-states-wc'),
                __('Bechloul', 'algeria-states-wc'),
                __('Bir Ghbalou', 'algeria-states-wc'),
                __('Bordj Okhriss', 'algeria-states-wc'),
                __('Bouderbala', 'algeria-states-wc'),
                __('Bouira', 'algeria-states-wc'),
                __('Boukram', 'algeria-states-wc'),
                __('Chorfa', 'algeria-states-wc'),
                __('Dechmia', 'algeria-states-wc'),
                __('Dirah', 'algeria-states-wc'),
                __('Djebahia', 'algeria-states-wc'),
                __('El Adjiba', 'algeria-states-wc'),
                __('El Asnam', 'algeria-states-wc'),
                __('El Hachimia', 'algeria-states-wc'),
                __('El Khabouzia', 'algeria-states-wc'),
                __('El-Hakimia', 'algeria-states-wc'),
                __('El-Mokrani', 'algeria-states-wc'),
                __('Guerrouma', 'algeria-states-wc'),
                __('Hadjera Zerga', 'algeria-states-wc'),
                __('Haizer', 'algeria-states-wc'),
                __('Hanif', 'algeria-states-wc'),
                __('Kadiria', 'algeria-states-wc'),
                __('Lakhdaria', 'algeria-states-wc'),
                __('M Chedallah', 'algeria-states-wc'),
                __('Maala', 'algeria-states-wc'),
                __('Maamora', 'algeria-states-wc'),
                __('Mezdour', 'algeria-states-wc'),
                __('Oued El Berdi', 'algeria-states-wc'),
                __('Ouled Rached', 'algeria-states-wc'),
                __('Raouraoua', 'algeria-states-wc'),
                __('Ridane', 'algeria-states-wc'),
                __('Saharidj', 'algeria-states-wc'),
                __('Souk El Khemis', 'algeria-states-wc'),
                __('Sour El Ghozlane', 'algeria-states-wc'),
                __('Taghzout', 'algeria-states-wc'),
                __('Taguedite', 'algeria-states-wc'),
                __('Zbarbar (El Isseri )', 'algeria-states-wc'),
            ),
            '11' => array(
                __('Abelsa', 'algeria-states-wc'),
                __('Ain Amguel', 'algeria-states-wc'),
                __('Idles', 'algeria-states-wc'),
                __('Tamanrasset', 'algeria-states-wc'),
                __('Tazrouk', 'algeria-states-wc'),
            ),
            '12' => array(
                __('Ain Zerga', 'algeria-states-wc'),
                __('Bedjene', 'algeria-states-wc'),
                __('Bekkaria', 'algeria-states-wc'),
                __('Bir Dheheb', 'algeria-states-wc'),
                __('Bir Mokkadem', 'algeria-states-wc'),
                __('Bir-El-Ater', 'algeria-states-wc'),
                __('Boukhadra', 'algeria-states-wc'),
                __('Boulhaf Dyr', 'algeria-states-wc'),
                __('Cheria', 'algeria-states-wc'),
                __('El Kouif', 'algeria-states-wc'),
                __('El Malabiod', 'algeria-states-wc'),
                __('El Meridj', 'algeria-states-wc'),
                __('El Mezeraa', 'algeria-states-wc'),
                __('El Ogla', 'algeria-states-wc'),
                __('El Ogla El Malha', 'algeria-states-wc'),
                __('El-Aouinet', 'algeria-states-wc'),
                __('El-Houidjbet', 'algeria-states-wc'),
                __('Ferkane', 'algeria-states-wc'),
                __('Guorriguer', 'algeria-states-wc'),
                __('Hammamet', 'algeria-states-wc'),
                __('Morsott', 'algeria-states-wc'),
                __('Negrine', 'algeria-states-wc'),
                __('Ouenza', 'algeria-states-wc'),
                __('Oum Ali', 'algeria-states-wc'),
                __('Saf Saf El Ouesra', 'algeria-states-wc'),
                __('Stah Guentis', 'algeria-states-wc'),
                __('Tebessa', 'algeria-states-wc'),
                __('Telidjen', 'algeria-states-wc'),
            ),
            '13' => array(
                __('Ain Fetah', 'algeria-states-wc'),
                __('Ain Fezza', 'algeria-states-wc'),
                __('Ain Ghoraba', 'algeria-states-wc'),
                __('Ain Kebira', 'algeria-states-wc'),
                __('Ain Nehala', 'algeria-states-wc'),
                __('Ain Tellout', 'algeria-states-wc'),
                __('Ain Youcef', 'algeria-states-wc'),
                __('Amieur', 'algeria-states-wc'),
                __('Azail', 'algeria-states-wc'),
                __('Bab El Assa', 'algeria-states-wc'),
                __('Beni Bahdel', 'algeria-states-wc'),
                __('Beni Boussaid', 'algeria-states-wc'),
                __('Beni Khellad', 'algeria-states-wc'),
                __('Beni Mester', 'algeria-states-wc'),
                __('Beni Ouarsous', 'algeria-states-wc'),
                __('Beni Smiel', 'algeria-states-wc'),
                __('Beni Snous', 'algeria-states-wc'),
                __('Bensekrane', 'algeria-states-wc'),
                __('Bouhlou', 'algeria-states-wc'),
                __('Bouihi', 'algeria-states-wc'),
                __('Chetouane', 'algeria-states-wc'),
                __('Dar Yaghmoracen', 'algeria-states-wc'),
                __('Djebala', 'algeria-states-wc'),
                __('El Aricha', 'algeria-states-wc'),
                __('El Fehoul', 'algeria-states-wc'),
                __('El Gor', 'algeria-states-wc'),
                __('Fellaoucene', 'algeria-states-wc'),
                __('Ghazaouet', 'algeria-states-wc'),
                __('Hammam Boughrara', 'algeria-states-wc'),
                __('Hennaya', 'algeria-states-wc'),
                __('Honnaine', 'algeria-states-wc'),
                __('Msirda Fouaga', 'algeria-states-wc'),
                __('Maghnia', 'algeria-states-wc'),
                __('Mansourah', 'algeria-states-wc'),
                __('Marsa Ben Mhidi', 'algeria-states-wc'),
                __('Nedroma', 'algeria-states-wc'),
                __('Oued Lakhdar', 'algeria-states-wc'),
                __('Ouled Mimoun', 'algeria-states-wc'),
                __('Ouled Riyah', 'algeria-states-wc'),
                __('Remchi', 'algeria-states-wc'),
                __('Sabra', 'algeria-states-wc'),
                __('Sebbaa Chioukh', 'algeria-states-wc'),
                __('Sebdou', 'algeria-states-wc'),
                __('Sidi Abdelli', 'algeria-states-wc'),
                __('Sidi Djillali', 'algeria-states-wc'),
                __('Sidi Medjahed', 'algeria-states-wc'),
                __('Souahlia', 'algeria-states-wc'),
                __('Souani', 'algeria-states-wc'),
                __('Souk Tleta', 'algeria-states-wc'),
                __('Terny Beni Hediel', 'algeria-states-wc'),
                __('Tianet', 'algeria-states-wc'),
                __('Tlemcen', 'algeria-states-wc'),
                __('Zenata', 'algeria-states-wc'),
            ),
            '14' => array(
                __('Ain Bouchekif', 'algeria-states-wc'),
                __('Ain Deheb', 'algeria-states-wc'),
                __('Ain Dzarit', 'algeria-states-wc'),
                __('Ain El Hadid', 'algeria-states-wc'),
                __('Ain Kermes', 'algeria-states-wc'),
                __('Bougara', 'algeria-states-wc'),
                __('Chehaima', 'algeria-states-wc'),
                __('Dahmouni', 'algeria-states-wc'),
                __('Djebilet Rosfa', 'algeria-states-wc'),
                __('Djillali Ben Amar', 'algeria-states-wc'),
                __('Faidja', 'algeria-states-wc'),
                __('Frenda', 'algeria-states-wc'),
                __('Guertoufa', 'algeria-states-wc'),
                __('Hamadia', 'algeria-states-wc'),
                __('Ksar Chellala', 'algeria-states-wc'),
                __('Madna', 'algeria-states-wc'),
                __('Mahdia', 'algeria-states-wc'),
                __('Mechraa Safa', 'algeria-states-wc'),
                __('Medrissa', 'algeria-states-wc'),
                __('Medroussa', 'algeria-states-wc'),
                __('Meghila', 'algeria-states-wc'),
                __('Mellakou', 'algeria-states-wc'),
                __('Nadorah', 'algeria-states-wc'),
                __('Naima', 'algeria-states-wc'),
                __('Oued Lilli', 'algeria-states-wc'),
                __('Rahouia', 'algeria-states-wc'),
                __('Rechaiga', 'algeria-states-wc'),
                __('Sebaine', 'algeria-states-wc'),
                __('Sebt', 'algeria-states-wc'),
                __('Serghine', 'algeria-states-wc'),
                __('Si Abdelghani', 'algeria-states-wc'),
                __('Sidi Abderrahmane', 'algeria-states-wc'),
                __('Sidi Ali Mellal', 'algeria-states-wc'),
                __('Sidi Bakhti', 'algeria-states-wc'),
                __('Sidi Hosni', 'algeria-states-wc'),
                __('Sougueur', 'algeria-states-wc'),
                __('Tagdempt', 'algeria-states-wc'),
                __('Takhemaret', 'algeria-states-wc'),
                __('Tiaret', 'algeria-states-wc'),
                __('Tidda', 'algeria-states-wc'),
                __('Tousnina', 'algeria-states-wc'),
                __('Zmalet El Emir Abdelkade', 'algeria-states-wc'),
            ),
            '15' => array(
                __('Abi-Youcef', 'algeria-states-wc'),
                __('Aghribs', 'algeria-states-wc'),
                __('Agouni-Gueghrane', 'algeria-states-wc'),
                __('Ain-El-Hammam', 'algeria-states-wc'),
                __('Ain-Zaouia', 'algeria-states-wc'),
                __('Ait Aggouacha', 'algeria-states-wc'),
                __('Ait Bouaddou', 'algeria-states-wc'),
                __('Ait Boumahdi', 'algeria-states-wc'),
                __('Ait Khellili', 'algeria-states-wc'),
                __('Ait Yahia Moussa', 'algeria-states-wc'),
                __('Ait-Aissa-Mimoun', 'algeria-states-wc'),
                __('Ait-Chafaa', 'algeria-states-wc'),
                __('Ait-Mahmoud', 'algeria-states-wc'),
                __('Ait-Oumalou', 'algeria-states-wc'),
                __('Ait-Toudert', 'algeria-states-wc'),
                __('Ait-Yahia', 'algeria-states-wc'),
                __('Akbil', 'algeria-states-wc'),
                __('Akerrou', 'algeria-states-wc'),
                __('Assi-Youcef', 'algeria-states-wc'),
                __('Azazga', 'algeria-states-wc'),
                __('Azeffoun', 'algeria-states-wc'),
                __('Beni Zmenzer', 'algeria-states-wc'),
                __('Beni Aissi', 'algeria-states-wc'),
                __('Beni Douala', 'algeria-states-wc'),
                __('Beni Yenni', 'algeria-states-wc'),
                __('Beni Zikki', 'algeria-states-wc'),
                __('Boghni', 'algeria-states-wc'),
                __('Boudjima', 'algeria-states-wc'),
                __('Bounouh', 'algeria-states-wc'),
                __('Bouzeguene', 'algeria-states-wc'),
                __('Draa-Ben-Khedda', 'algeria-states-wc'),
                __('Draa-El-Mizan', 'algeria-states-wc'),
                __('Freha', 'algeria-states-wc'),
                __('Frikat', 'algeria-states-wc'),
                __('Iboudrarene', 'algeria-states-wc'),
                __('Idjeur', 'algeria-states-wc'),
                __('Iferhounene', 'algeria-states-wc'),
                __('Ifigha', 'algeria-states-wc'),
                __('Iflissen', 'algeria-states-wc'),
                __('Illilten', 'algeria-states-wc'),
                __('Illoula Oumalou', 'algeria-states-wc'),
                __('Imsouhal', 'algeria-states-wc'),
                __('Irdjen', 'algeria-states-wc'),
                __('Larbaa Nath Irathen', 'algeria-states-wc'),
                __('Mkira', 'algeria-states-wc'),
                __('Maatkas', 'algeria-states-wc'),
                __('Makouda', 'algeria-states-wc'),
                __('Mechtras', 'algeria-states-wc'),
                __('Mekla', 'algeria-states-wc'),
                __('Mizrana', 'algeria-states-wc'),
                __('Ouacif', 'algeria-states-wc'),
                __('Ouadhias', 'algeria-states-wc'),
                __('Ouaguenoun', 'algeria-states-wc'),
                __('Sidi Namane', 'algeria-states-wc'),
                __('Souama', 'algeria-states-wc'),
                __('Souk-El-Tenine', 'algeria-states-wc'),
                __('Tadmait', 'algeria-states-wc'),
                __('Tigzirt', 'algeria-states-wc'),
                __('Timizart', 'algeria-states-wc'),
                __('Tirmitine', 'algeria-states-wc'),
                __('Tizi Ntleta', 'algeria-states-wc'),
                __('Tizi Gheniff', 'algeria-states-wc'),
                __('Tizi Ouzou', 'algeria-states-wc'),
                __('Tizi Rached', 'algeria-states-wc'),
                __('Yakourene', 'algeria-states-wc'),
                __('Yatafene', 'algeria-states-wc'),
                __('Zekri', 'algeria-states-wc'),
            ),
            '16' => array(
                __('Ain Benian', 'algeria-states-wc'),
                __('Ain Taya', 'algeria-states-wc'),
                __('Alger Centre', 'algeria-states-wc'),
                __('Bab El Oued', 'algeria-states-wc'),
                __('Bab Ezzouar', 'algeria-states-wc'),
                __('Baba Hassen', 'algeria-states-wc'),
                __('Bachedjerah', 'algeria-states-wc'),
                __('Baraki', 'algeria-states-wc'),
                __('Ben Aknoun', 'algeria-states-wc'),
                __('Beni Messous', 'algeria-states-wc'),
                __('Bir Mourad Rais', 'algeria-states-wc'),
                __('Bir Touta', 'algeria-states-wc'),
                __('Birkhadem', 'algeria-states-wc'),
                __('Bologhine Ibnou Ziri', 'algeria-states-wc'),
                __('Bordj El Bahri', 'algeria-states-wc'),
                __('Bordj El Kiffan', 'algeria-states-wc'),
                __('Bourouba', 'algeria-states-wc'),
                __('Bouzareah', 'algeria-states-wc'),
                __('Casbah', 'algeria-states-wc'),
                __('Cheraga', 'algeria-states-wc'),
                __('Dar El Beida', 'algeria-states-wc'),
                __('Dely Ibrahim', 'algeria-states-wc'),
                __('Djasr Kasentina', 'algeria-states-wc'),
                __('Douira', 'algeria-states-wc'),
                __('Draria', 'algeria-states-wc'),
                __('El Achour', 'algeria-states-wc'),
                __('El Biar', 'algeria-states-wc'),
                __('El Harrach', 'algeria-states-wc'),
                __('El Madania', 'algeria-states-wc'),
                __('El Magharia', 'algeria-states-wc'),
                __('El Marsa', 'algeria-states-wc'),
                __('El Mouradia', 'algeria-states-wc'),
                __('Hammamet', 'algeria-states-wc'),
                __('Herraoua', 'algeria-states-wc'),
                __('Hussein Dey', 'algeria-states-wc'),
                __('Hydra', 'algeria-states-wc'),
                __('Khraissia', 'algeria-states-wc'),
                __('Kouba', 'algeria-states-wc'),
                __('Les Eucalyptus', 'algeria-states-wc'),
                __('Maalma', 'algeria-states-wc'),
                __('Mohamed Belouzdad', 'algeria-states-wc'),
                __('Mohammadia', 'algeria-states-wc'),
                __('Oued Koriche', 'algeria-states-wc'),
                __('Oued Smar', 'algeria-states-wc'),
                __('Ouled Chebel', 'algeria-states-wc'),
                __('Ouled Fayet', 'algeria-states-wc'),
                __('Rahmania', 'algeria-states-wc'),
                __('Rais Hamidou', 'algeria-states-wc'),
                __('Reghaia', 'algeria-states-wc'),
                __('Rouiba', 'algeria-states-wc'),
                __('Sehaoula', 'algeria-states-wc'),
                __('Sidi Mhamed', 'algeria-states-wc'),
                __('Sidi Moussa', 'algeria-states-wc'),
                __('Souidania', 'algeria-states-wc'),
                __('Staoueli', 'algeria-states-wc'),
                __('Tessala El Merdja', 'algeria-states-wc'),
                __('Zeralda', 'algeria-states-wc'),
            ),
            '17' => array(
                __('Ain Chouhada', 'algeria-states-wc'),
                __('Ain El Ibel', 'algeria-states-wc'),
                __('Ain Fekka', 'algeria-states-wc'),
                __('Ain Maabed', 'algeria-states-wc'),
                __('Ain Oussera', 'algeria-states-wc'),
                __('Amourah', 'algeria-states-wc'),
                __('Benhar', 'algeria-states-wc'),
                __('Benyagoub', 'algeria-states-wc'),
                __('Birine', 'algeria-states-wc'),
                __('Bouira Lahdab', 'algeria-states-wc'),
                __('Charef', 'algeria-states-wc'),
                __('Dar Chioukh', 'algeria-states-wc'),
                __('Deldoul', 'algeria-states-wc'),
                __('Djelfa', 'algeria-states-wc'),
                __('Douis', 'algeria-states-wc'),
                __('El Guedid', 'algeria-states-wc'),
                __('El Idrissia', 'algeria-states-wc'),
                __('El Khemis', 'algeria-states-wc'),
                __('Faidh El Botma', 'algeria-states-wc'),
                __('Guernini', 'algeria-states-wc'),
                __('Guettara', 'algeria-states-wc'),
                __('Had Sahary', 'algeria-states-wc'),
                __('Hassi Bahbah', 'algeria-states-wc'),
                __('Hassi El Euch', 'algeria-states-wc'),
                __('Hassi Fedoul', 'algeria-states-wc'),
                __('Mliliha', 'algeria-states-wc'),
                __('Messaad', 'algeria-states-wc'),
                __('Moudjebara', 'algeria-states-wc'),
                __('Oum Laadham', 'algeria-states-wc'),
                __('Sed Rahal', 'algeria-states-wc'),
                __('Selmana', 'algeria-states-wc'),
                __('Sidi Baizid', 'algeria-states-wc'),
                __('Sidi Laadjel', 'algeria-states-wc'),
                __('Taadmit', 'algeria-states-wc'),
                __('Zaafrane', 'algeria-states-wc'),
                __('Zaccar', 'algeria-states-wc'),
            ),
            '18' => array(
                __('Bordj Thar', 'algeria-states-wc'),
                __('Boudria Beniyadjis', 'algeria-states-wc'),
                __('Bouraoui Belhadef', 'algeria-states-wc'),
                __('Boussif Ouled Askeur', 'algeria-states-wc'),
                __('Chahna', 'algeria-states-wc'),
                __('Chekfa', 'algeria-states-wc'),
                __('Djemaa Beni Habibi', 'algeria-states-wc'),
                __('Djimla', 'algeria-states-wc'),
                __('El Ancer', 'algeria-states-wc'),
                __('El Aouana', 'algeria-states-wc'),
                __('El Kennar Nouchfi', 'algeria-states-wc'),
                __('El Milia', 'algeria-states-wc'),
                __('Emir Abdelkader', 'algeria-states-wc'),
                __('Erraguene Souissi', 'algeria-states-wc'),
                __('Ghebala', 'algeria-states-wc'),
                __('Jijel', 'algeria-states-wc'),
                __('Kaous', 'algeria-states-wc'),
                __('Khiri Oued Adjoul', 'algeria-states-wc'),
                __('Oudjana', 'algeria-states-wc'),
                __('Ouled Rabah', 'algeria-states-wc'),
                __('Ouled Yahia Khadrouch', 'algeria-states-wc'),
                __('Selma Benziada', 'algeria-states-wc'),
                __('Settara', 'algeria-states-wc'),
                __('Sidi Abdelaziz', 'algeria-states-wc'),
                __('Sidi Marouf', 'algeria-states-wc'),
                __('Taher', 'algeria-states-wc'),
                __('Texenna', 'algeria-states-wc'),
                __('Ziama Mansouriah', 'algeria-states-wc'),
            ),
            '19' => array(
                __('Ain Abessa', 'algeria-states-wc'),
                __('Ain Arnat', 'algeria-states-wc'),
                __('Ain Azel', 'algeria-states-wc'),
                __('Ain El Kebira', 'algeria-states-wc'),
                __('Ain Lahdjar', 'algeria-states-wc'),
                __('Ain Oulmene', 'algeria-states-wc'),
                __('Ain-Legradj', 'algeria-states-wc'),
                __('Ain-Roua', 'algeria-states-wc'),
                __('Ain-Sebt', 'algeria-states-wc'),
                __('Ait Naoual Mezada', 'algeria-states-wc'),
                __('Ait-Tizi', 'algeria-states-wc'),
                __('Amoucha', 'algeria-states-wc'),
                __('Babor', 'algeria-states-wc'),
                __('Bazer-Sakra', 'algeria-states-wc'),
                __('Beidha Bordj', 'algeria-states-wc'),
                __('Bellaa', 'algeria-states-wc'),
                __('Beni Chebana', 'algeria-states-wc'),
                __('Beni Fouda', 'algeria-states-wc'),
                __('Beni Ourtilane', 'algeria-states-wc'),
                __('Beni Oussine', 'algeria-states-wc'),
                __('Beni-Aziz', 'algeria-states-wc'),
                __('Beni-Mouhli', 'algeria-states-wc'),
                __('Bir Haddada', 'algeria-states-wc'),
                __('Bir-El-Arch', 'algeria-states-wc'),
                __('Bouandas', 'algeria-states-wc'),
                __('Bougaa', 'algeria-states-wc'),
                __('Bousselam', 'algeria-states-wc'),
                __('Boutaleb', 'algeria-states-wc'),
                __('Dehamcha', 'algeria-states-wc'),
                __('Djemila', 'algeria-states-wc'),
                __('Draa-Kebila', 'algeria-states-wc'),
                __('El Eulma', 'algeria-states-wc'),
                __('El Ouricia', 'algeria-states-wc'),
                __('El-Ouldja', 'algeria-states-wc'),
                __('Guellal', 'algeria-states-wc'),
                __('Guelta Zerka', 'algeria-states-wc'),
                __('Guenzet', 'algeria-states-wc'),
                __('Guidjel', 'algeria-states-wc'),
                __('Hamam Soukhna', 'algeria-states-wc'),
                __('Hamma', 'algeria-states-wc'),
                __('Hammam Guergour', 'algeria-states-wc'),
                __('Harbil', 'algeria-states-wc'),
                __('Kasr El Abtal', 'algeria-states-wc'),
                __('Maaouia', 'algeria-states-wc'),
                __('Maouaklane', 'algeria-states-wc'),
                __('Mezloug', 'algeria-states-wc'),
                __('Oued El Bared', 'algeria-states-wc'),
                __('Ouled Addouane', 'algeria-states-wc'),
                __('Ouled Sabor', 'algeria-states-wc'),
                __('Ouled Si Ahmed', 'algeria-states-wc'),
                __('Ouled Tebben', 'algeria-states-wc'),
                __('Rosfa', 'algeria-states-wc'),
                __('Salah Bey', 'algeria-states-wc'),
                __('Serdj-El-Ghoul', 'algeria-states-wc'),
                __('Setif', 'algeria-states-wc'),
                __('Tachouda', 'algeria-states-wc'),
                __('Tala-Ifacene', 'algeria-states-wc'),
                __('Taya', 'algeria-states-wc'),
                __('Tella', 'algeria-states-wc'),
                __('Tizi Nbechar', 'algeria-states-wc'),
            ),
            '20' => array(
                __('Ain El Hadjar', 'algeria-states-wc'),
                __('Ain Sekhouna', 'algeria-states-wc'),
                __('Ain Soltane', 'algeria-states-wc'),
                __('Doui Thabet', 'algeria-states-wc'),
                __('El Hassasna', 'algeria-states-wc'),
                __('Hounet', 'algeria-states-wc'),
                __('Maamora', 'algeria-states-wc'),
                __('Moulay Larbi', 'algeria-states-wc'),
                __('Ouled Brahim', 'algeria-states-wc'),
                __('Ouled Khaled', 'algeria-states-wc'),
                __('Saida', 'algeria-states-wc'),
                __('Sidi Ahmed', 'algeria-states-wc'),
                __('Sidi Amar', 'algeria-states-wc'),
                __('Sidi Boubekeur', 'algeria-states-wc'),
                __('Tircine', 'algeria-states-wc'),
                __('Youb', 'algeria-states-wc'),
            ),
            '21' => array(
                __('Ain Bouziane', 'algeria-states-wc'),
                __('Ain Charchar', 'algeria-states-wc'),
                __('Ain Kechra', 'algeria-states-wc'),
                __('Ain Zouit', 'algeria-states-wc'),
                __('Azzaba', 'algeria-states-wc'),
                __('Bekkouche Lakhdar', 'algeria-states-wc'),
                __('Ben Azzouz', 'algeria-states-wc'),
                __('Beni Bechir', 'algeria-states-wc'),
                __('Beni Oulbane', 'algeria-states-wc'),
                __('Beni Zid', 'algeria-states-wc'),
                __('Bin El Ouiden', 'algeria-states-wc'),
                __('Bouchetata', 'algeria-states-wc'),
                __('Cheraia', 'algeria-states-wc'),
                __('Collo', 'algeria-states-wc'),
                __('Djendel Saadi Mohamed', 'algeria-states-wc'),
                __('El Arrouch', 'algeria-states-wc'),
                __('El Ghedir', 'algeria-states-wc'),
                __('El Hadaiek', 'algeria-states-wc'),
                __('El Marsa', 'algeria-states-wc'),
                __('Emjez Edchich', 'algeria-states-wc'),
                __('Es Sebt', 'algeria-states-wc'),
                __('Filfila', 'algeria-states-wc'),
                __('Hammadi Krouma', 'algeria-states-wc'),
                __('Kanoua', 'algeria-states-wc'),
                __('Kerkara', 'algeria-states-wc'),
                __('Khenag Maoune', 'algeria-states-wc'),
                __('Oued Zhour', 'algeria-states-wc'),
                __('Ouldja Boulbalout', 'algeria-states-wc'),
                __('Ouled Attia', 'algeria-states-wc'),
                __('Ouled Habbaba', 'algeria-states-wc'),
                __('Oum Toub', 'algeria-states-wc'),
                __('Ramdane Djamel', 'algeria-states-wc'),
                __('Salah Bouchaour', 'algeria-states-wc'),
                __('Sidi Mezghiche', 'algeria-states-wc'),
                __('Skikda', 'algeria-states-wc'),
                __('Tamalous', 'algeria-states-wc'),
                __('Zerdezas', 'algeria-states-wc'),
                __('Zitouna', 'algeria-states-wc'),
            ),
            '22' => array(
                __('Ain El Berd', 'algeria-states-wc'),
                __('Ain Kada', 'algeria-states-wc'),
                __('Ain Thrid', 'algeria-states-wc'),
                __('Ain Tindamine', 'algeria-states-wc'),
                __('Ain- Adden', 'algeria-states-wc'),
                __('Amarnas', 'algeria-states-wc'),
                __('Bedrabine El Mokrani', 'algeria-states-wc'),
                __('Belarbi', 'algeria-states-wc'),
                __('Ben Badis', 'algeria-states-wc'),
                __('Benachiba Chelia', 'algeria-states-wc'),
                __('Bir El Hammam', 'algeria-states-wc'),
                __('Boudjebaa El Bordj', 'algeria-states-wc'),
                __('Boukhanefis', 'algeria-states-wc'),
                __('Chetouane Belaila', 'algeria-states-wc'),
                __('Dhaya', 'algeria-states-wc'),
                __('El Hacaiba', 'algeria-states-wc'),
                __('Hassi Dahou', 'algeria-states-wc'),
                __('Hassi Zahana', 'algeria-states-wc'),
                __('Lamtar', 'algeria-states-wc'),
                __('Mcid', 'algeria-states-wc'),
                __('Makedra', 'algeria-states-wc'),
                __('Marhoum', 'algeria-states-wc'),
                __('Merine', 'algeria-states-wc'),
                __('Mezaourou', 'algeria-states-wc'),
                __('Mostefa  Ben Brahim', 'algeria-states-wc'),
                __('Moulay Slissen', 'algeria-states-wc'),
                __('Oued Sebaa', 'algeria-states-wc'),
                __('Oued Sefioun', 'algeria-states-wc'),
                __('Oued Taourira', 'algeria-states-wc'),
                __('Ras El Ma', 'algeria-states-wc'),
                __('Redjem Demouche', 'algeria-states-wc'),
                __('Sehala Thaoura', 'algeria-states-wc'),
                __('Sfisef', 'algeria-states-wc'),
                __('Sidi Ali Benyoub', 'algeria-states-wc'),
                __('Sidi Ali Boussidi', 'algeria-states-wc'),
                __('Sidi Bel-Abbes', 'algeria-states-wc'),
                __('Sidi Brahim', 'algeria-states-wc'),
                __('Sidi Chaib', 'algeria-states-wc'),
                __('Sidi Dahou Zairs', 'algeria-states-wc'),
                __('Sidi Hamadouche', 'algeria-states-wc'),
                __('Sidi Khaled', 'algeria-states-wc'),
                __('Sidi Lahcene', 'algeria-states-wc'),
                __('Sidi Yacoub', 'algeria-states-wc'),
                __('Tabia', 'algeria-states-wc'),
                __('Taoudmout', 'algeria-states-wc'),
                __('Tefessour', 'algeria-states-wc'),
                __('Teghalimet', 'algeria-states-wc'),
                __('Telagh', 'algeria-states-wc'),
                __('Tenira', 'algeria-states-wc'),
                __('Tessala', 'algeria-states-wc'),
                __('Tilmouni', 'algeria-states-wc'),
                __('Zerouala', 'algeria-states-wc'),
            ),
            '23' => array(
                __('Ain El Berda', 'algeria-states-wc'),
                __('Annaba', 'algeria-states-wc'),
                __('Berrahal', 'algeria-states-wc'),
                __('Chetaibi', 'algeria-states-wc'),
                __('Cheurfa', 'algeria-states-wc'),
                __('El Bouni', 'algeria-states-wc'),
                __('El Eulma', 'algeria-states-wc'),
                __('El Hadjar', 'algeria-states-wc'),
                __('Oued El Aneb', 'algeria-states-wc'),
                __('Seraidi', 'algeria-states-wc'),
                __('Sidi Amar', 'algeria-states-wc'),
                __('Treat', 'algeria-states-wc'),
            ),
            '24' => array(
                __('Ain Ben Beida', 'algeria-states-wc'),
                __('Ain Larbi', 'algeria-states-wc'),
                __('Ain Makhlouf', 'algeria-states-wc'),
                __('Ain Regada', 'algeria-states-wc'),
                __('Ain Sandel', 'algeria-states-wc'),
                __('Belkheir', 'algeria-states-wc'),
                __('Bendjarah', 'algeria-states-wc'),
                __('Beni Mezline', 'algeria-states-wc'),
                __('Bordj Sabath', 'algeria-states-wc'),
                __('Bou Hachana', 'algeria-states-wc'),
                __('Bou Hamdane', 'algeria-states-wc'),
                __('Bouati Mahmoud', 'algeria-states-wc'),
                __('Bouchegouf', 'algeria-states-wc'),
                __('Boumahra Ahmed', 'algeria-states-wc'),
                __('Dahouara', 'algeria-states-wc'),
                __('Djeballah Khemissi', 'algeria-states-wc'),
                __('El Fedjoudj', 'algeria-states-wc'),
                __('Guelaat Bou Sbaa', 'algeria-states-wc'),
                __('Guelma', 'algeria-states-wc'),
                __('Hammam Debagh', 'algeria-states-wc'),
                __('Hammam Nbail', 'algeria-states-wc'),
                __('Heliopolis', 'algeria-states-wc'),
                __('Houari Boumedienne', 'algeria-states-wc'),
                __('Khezaras', 'algeria-states-wc'),
                __('Medjez Amar', 'algeria-states-wc'),
                __('Medjez Sfa', 'algeria-states-wc'),
                __('Nechmaya', 'algeria-states-wc'),
                __('Oued Cheham', 'algeria-states-wc'),
                __('Oued Ferragha', 'algeria-states-wc'),
                __('Oued Zenati', 'algeria-states-wc'),
                __('Ras El Agba', 'algeria-states-wc'),
                __('Roknia', 'algeria-states-wc'),
                __('Sellaoua Announa', 'algeria-states-wc'),
                __('Tamlouka', 'algeria-states-wc'),
            ),
            '25' => array(
                __('Ain Abid', 'algeria-states-wc'),
                __('Ain Smara', 'algeria-states-wc'),
                __('Ben Badis', 'algeria-states-wc'),
                __('Beni Hamidane', 'algeria-states-wc'),
                __('Constantine', 'algeria-states-wc'),
                __('Didouche Mourad', 'algeria-states-wc'),
                __('El Khroub', 'algeria-states-wc'),
                __('Hamma Bouziane', 'algeria-states-wc'),
                __('Ibn Ziad', 'algeria-states-wc'),
                __('Messaoud Boudjeriou', 'algeria-states-wc'),
                __('Ouled Rahmoun', 'algeria-states-wc'),
                __('Zighoud Youcef', 'algeria-states-wc'),
            ),
            '26' => array(
                __('Ain Boucif', 'algeria-states-wc'),
                __('Ain Ouksir', 'algeria-states-wc'),
                __('Aissaouia', 'algeria-states-wc'),
                __('Aziz', 'algeria-states-wc'),
                __('Baata', 'algeria-states-wc'),
                __('Ben Chicao', 'algeria-states-wc'),
                __('Beni Slimane', 'algeria-states-wc'),
                __('Berrouaghia', 'algeria-states-wc'),
                __('Bir Ben Laabed', 'algeria-states-wc'),
                __('Boghar', 'algeria-states-wc'),
                __('Bouaiche', 'algeria-states-wc'),
                __('Bouaichoune', 'algeria-states-wc'),
                __('Bouchrahil', 'algeria-states-wc'),
                __('Boughzoul', 'algeria-states-wc'),
                __('Bouskene', 'algeria-states-wc'),
                __('Chabounia', 'algeria-states-wc'),
                __('Chelalet El Adhaoura', 'algeria-states-wc'),
                __('Cheniguel', 'algeria-states-wc'),
                __('Derrag', 'algeria-states-wc'),
                __('Djouab', 'algeria-states-wc'),
                __('Draa Esmar', 'algeria-states-wc'),
                __('El Azizia', 'algeria-states-wc'),
                __('El Guelbelkebir', 'algeria-states-wc'),
                __('El Hamdania', 'algeria-states-wc'),
                __('El Haoudane', 'algeria-states-wc'),
                __('El Omaria', 'algeria-states-wc'),
                __('El Ouinet', 'algeria-states-wc'),
                __('Hannacha', 'algeria-states-wc'),
                __('Kef Lakhdar', 'algeria-states-wc'),
                __('Khams Djouamaa', 'algeria-states-wc'),
                __('Ksar El Boukhari', 'algeria-states-wc'),
                __('Mfatha', 'algeria-states-wc'),
                __('Maghraoua', 'algeria-states-wc'),
                __('Medea', 'algeria-states-wc'),
                __('Medjebar', 'algeria-states-wc'),
                __('Mezerana', 'algeria-states-wc'),
                __('Mihoub', 'algeria-states-wc'),
                __('Ouamri', 'algeria-states-wc'),
                __('Oued Harbil', 'algeria-states-wc'),
                __('Ouled Antar', 'algeria-states-wc'),
                __('Ouled Bouachra', 'algeria-states-wc'),
                __('Ouled Brahim', 'algeria-states-wc'),
                __('Ouled Deid', 'algeria-states-wc'),
                __('Ouled Emaaraf', 'algeria-states-wc'),
                __('Ouled Hellal', 'algeria-states-wc'),
                __('Oum El Djellil', 'algeria-states-wc'),
                __('Ouzera', 'algeria-states-wc'),
                __('Rebaia', 'algeria-states-wc'),
                __('Saneg', 'algeria-states-wc'),
                __('Sedraya', 'algeria-states-wc'),
                __('Seghouane', 'algeria-states-wc'),
                __('Si Mahdjoub', 'algeria-states-wc'),
                __('Sidi Demed', 'algeria-states-wc'),
                __('Sidi Naamane', 'algeria-states-wc'),
                __('Sidi Rabie', 'algeria-states-wc'),
                __('Sidi Zahar', 'algeria-states-wc'),
                __('Sidi Ziane', 'algeria-states-wc'),
                __('Souagui', 'algeria-states-wc'),
                __('Tablat', 'algeria-states-wc'),
                __('Tafraout', 'algeria-states-wc'),
                __('Tamesguida', 'algeria-states-wc'),
                __('Tizi Mahdi', 'algeria-states-wc'),
                __('Tletat Ed Douair', 'algeria-states-wc'),
                __('Zoubiria', 'algeria-states-wc'),
            ),
            '27' => array(
                __('Achaacha', 'algeria-states-wc'),
                __('Ain-Boudinar', 'algeria-states-wc'),
                __('Ain-Nouissy', 'algeria-states-wc'),
                __('Ain-Sidi Cherif', 'algeria-states-wc'),
                __('Ain-Tedles', 'algeria-states-wc'),
                __('Benabdelmalek Ramdane', 'algeria-states-wc'),
                __('Bouguirat', 'algeria-states-wc'),
                __('Fornaka', 'algeria-states-wc'),
                __('Hadjadj', 'algeria-states-wc'),
                __('Hassi Mameche', 'algeria-states-wc'),
                __('Hassiane', 'algeria-states-wc'),
                __('Khadra', 'algeria-states-wc'),
                __('Kheir-Eddine', 'algeria-states-wc'),
                __('Mansourah', 'algeria-states-wc'),
                __('Mazagran', 'algeria-states-wc'),
                __('Mesra', 'algeria-states-wc'),
                __('Mostaganem', 'algeria-states-wc'),
                __('Nekmaria', 'algeria-states-wc'),
                __('Oued El Kheir', 'algeria-states-wc'),
                __('Ouled Boughalem', 'algeria-states-wc'),
                __('Ouled-Maalah', 'algeria-states-wc'),
                __('Safsaf', 'algeria-states-wc'),
                __('Sayada', 'algeria-states-wc'),
                __('Sidi Ali', 'algeria-states-wc'),
                __('Sidi Belaattar', 'algeria-states-wc'),
                __('Sidi-Lakhdar', 'algeria-states-wc'),
                __('Sirat', 'algeria-states-wc'),
                __('Souaflia', 'algeria-states-wc'),
                __('Sour', 'algeria-states-wc'),
                __('Stidia', 'algeria-states-wc'),
                __('Tazgait', 'algeria-states-wc'),
                __('Touahria', 'algeria-states-wc'),
            ),
            '28' => array(
                __('Ain El Hadjel', 'algeria-states-wc'),
                __('Ain El Melh', 'algeria-states-wc'),
                __('Ain Fares', 'algeria-states-wc'),
                __('Ain Khadra', 'algeria-states-wc'),
                __('Ain Rich', 'algeria-states-wc'),
                __('Belaiba', 'algeria-states-wc'),
                __('Ben Srour', 'algeria-states-wc'),
                __('Beni Ilmane', 'algeria-states-wc'),
                __('Benzouh', 'algeria-states-wc'),
                __('Berhoum', 'algeria-states-wc'),
                __('Bir Foda', 'algeria-states-wc'),
                __('Bou Saada', 'algeria-states-wc'),
                __('Bouti Sayeh', 'algeria-states-wc'),
                __('Chellal', 'algeria-states-wc'),
                __('Dehahna', 'algeria-states-wc'),
                __('Djebel Messaad', 'algeria-states-wc'),
                __('El Hamel', 'algeria-states-wc'),
                __('El Houamed', 'algeria-states-wc'),
                __('Hammam Dalaa', 'algeria-states-wc'),
                __('Khettouti Sed-El-Jir', 'algeria-states-wc'),
                __('Khoubana', 'algeria-states-wc'),
                __('Mcif', 'algeria-states-wc'),
                __('Msila', 'algeria-states-wc'),
                __('Mtarfa', 'algeria-states-wc'),
                __('Maadid', 'algeria-states-wc'),
                __('Maarif', 'algeria-states-wc'),
                __('Magra', 'algeria-states-wc'),
                __('Medjedel', 'algeria-states-wc'),
                __('Menaa', 'algeria-states-wc'),
                __('Mohamed Boudiaf', 'algeria-states-wc'),
                __('Ouanougha', 'algeria-states-wc'),
                __('Ouled Addi Guebala', 'algeria-states-wc'),
                __('Ouled Derradj', 'algeria-states-wc'),
                __('Ouled Madhi', 'algeria-states-wc'),
                __('Ouled Mansour', 'algeria-states-wc'),
                __('Ouled Sidi Brahim', 'algeria-states-wc'),
                __('Ouled Slimane', 'algeria-states-wc'),
                __('Oulteme', 'algeria-states-wc'),
                __('Sidi Aissa', 'algeria-states-wc'),
                __('Sidi Ameur', 'algeria-states-wc'),
                __('Sidi Hadjeres', 'algeria-states-wc'),
                __('Sidi Mhamed', 'algeria-states-wc'),
                __('Slim', 'algeria-states-wc'),
                __('Souamaa', 'algeria-states-wc'),
                __('Tamsa', 'algeria-states-wc'),
                __('Tarmount', 'algeria-states-wc'),
                __('Zarzour', 'algeria-states-wc'),
            ),
            '29' => array(
                __('Ain Fares', 'algeria-states-wc'),
                __('Ain Fekan', 'algeria-states-wc'),
                __('Ain Ferah', 'algeria-states-wc'),
                __('Ain Frass', 'algeria-states-wc'),
                __('Alaimia', 'algeria-states-wc'),
                __('Aouf', 'algeria-states-wc'),
                __('Benian', 'algeria-states-wc'),
                __('Bou Henni', 'algeria-states-wc'),
                __('Bouhanifia', 'algeria-states-wc'),
                __('Chorfa', 'algeria-states-wc'),
                __('El Bordj', 'algeria-states-wc'),
                __('El Gaada', 'algeria-states-wc'),
                __('El Ghomri', 'algeria-states-wc'),
                __('El Gueitena', 'algeria-states-wc'),
                __('El Hachem', 'algeria-states-wc'),
                __('El Keurt', 'algeria-states-wc'),
                __('El Mamounia', 'algeria-states-wc'),
                __('El Menaouer', 'algeria-states-wc'),
                __('Ferraguig', 'algeria-states-wc'),
                __('Froha', 'algeria-states-wc'),
                __('Gharrous', 'algeria-states-wc'),
                __('Ghriss', 'algeria-states-wc'),
                __('Guerdjoum', 'algeria-states-wc'),
                __('Hacine', 'algeria-states-wc'),
                __('Khalouia', 'algeria-states-wc'),
                __('Makhda', 'algeria-states-wc'),
                __('Maoussa', 'algeria-states-wc'),
                __('Mascara', 'algeria-states-wc'),
                __('Matemore', 'algeria-states-wc'),
                __('Mocta-Douz', 'algeria-states-wc'),
                __('Mohammadia', 'algeria-states-wc'),
                __('Nesmot', 'algeria-states-wc'),
                __('Oggaz', 'algeria-states-wc'),
                __('Oued El Abtal', 'algeria-states-wc'),
                __('Oued Taria', 'algeria-states-wc'),
                __('Ras El Ain Amirouche', 'algeria-states-wc'),
                __('Sedjerara', 'algeria-states-wc'),
                __('Sehailia', 'algeria-states-wc'),
                __('Sidi Abdeldjebar', 'algeria-states-wc'),
                __('Sidi Abdelmoumene', 'algeria-states-wc'),
                __('Sidi Boussaid', 'algeria-states-wc'),
                __('Sidi Kada', 'algeria-states-wc'),
                __('Sig', 'algeria-states-wc'),
                __('Tighennif', 'algeria-states-wc'),
                __('Tizi', 'algeria-states-wc'),
                __('Zahana', 'algeria-states-wc'),
                __('Zelamta', 'algeria-states-wc'),
            ),
            '30' => array(
                __('Ain Beida', 'algeria-states-wc'),
                __('El Borma', 'algeria-states-wc'),
                __('Hassi Ben Abdellah', 'algeria-states-wc'),
                __('Hassi Messaoud', 'algeria-states-wc'),
                __('Ngoussa', 'algeria-states-wc'),
                __('Ouargla', 'algeria-states-wc'),
                __('Rouissat', 'algeria-states-wc'),
                __('Sidi Khouiled', 'algeria-states-wc'),
            ),
            '31' => array(
                __('Ain Biya', 'algeria-states-wc'),
                __('Ain Kerma', 'algeria-states-wc'),
                __('Ain Turk', 'algeria-states-wc'),
                __('Arzew', 'algeria-states-wc'),
                __('Ben Freha', 'algeria-states-wc'),
                __('Bethioua', 'algeria-states-wc'),
                __('Bir El Djir', 'algeria-states-wc'),
                __('Boufatis', 'algeria-states-wc'),
                __('Bousfer', 'algeria-states-wc'),
                __('Boutlelis', 'algeria-states-wc'),
                __('El Ancor', 'algeria-states-wc'),
                __('El Braya', 'algeria-states-wc'),
                __('El Kerma', 'algeria-states-wc'),
                __('Es Senia', 'algeria-states-wc'),
                __('Gdyel', 'algeria-states-wc'),
                __('Hassi Ben Okba', 'algeria-states-wc'),
                __('Hassi Bounif', 'algeria-states-wc'),
                __('Hassi Mefsoukh', 'algeria-states-wc'),
                __('Marsat El Hadjadj', 'algeria-states-wc'),
                __('Mers El Kebir', 'algeria-states-wc'),
                __('Messerghin', 'algeria-states-wc'),
                __('Oran', 'algeria-states-wc'),
                __('Oued Tlelat', 'algeria-states-wc'),
                __('Sidi Ben Yebka', 'algeria-states-wc'),
                __('Sidi Chami', 'algeria-states-wc'),
                __('Tafraoui', 'algeria-states-wc'),
            ),
            '32' => array(
                __('Ain El Orak', 'algeria-states-wc'),
                __('Arbaouat', 'algeria-states-wc'),
                __('Boualem', 'algeria-states-wc'),
                __('Bougtoub', 'algeria-states-wc'),
                __('Boussemghoun', 'algeria-states-wc'),
                __('Brezina', 'algeria-states-wc'),
                __('Cheguig', 'algeria-states-wc'),
                __('Chellala', 'algeria-states-wc'),
                __('El Bayadh', 'algeria-states-wc'),
                __('El Bnoud', 'algeria-states-wc'),
                __('El Kheiter', 'algeria-states-wc'),
                __('El Mehara', 'algeria-states-wc'),
                __('Ghassoul', 'algeria-states-wc'),
                __('Kef El Ahmar', 'algeria-states-wc'),
                __('Krakda', 'algeria-states-wc'),
                __('Labiodh Sidi Cheikh', 'algeria-states-wc'),
                __('Rogassa', 'algeria-states-wc'),
                __('Sidi Ameur', 'algeria-states-wc'),
                __('Sidi Slimane', 'algeria-states-wc'),
                __('Sidi Tiffour', 'algeria-states-wc'),
                __('Stitten', 'algeria-states-wc'),
                __('Tousmouline', 'algeria-states-wc'),
            ),
            '33' => array(
                __('Bordj Omar Driss', 'algeria-states-wc'),
                __('Debdeb', 'algeria-states-wc'),
                __('Illizi', 'algeria-states-wc'),
                __('In Amenas', 'algeria-states-wc'),
            ),
            '34' => array(
                __('Ain Taghrout', 'algeria-states-wc'),
                __('Ain Tesra', 'algeria-states-wc'),
                __('B. B. Arreridj', 'algeria-states-wc'),
                __('Belimour', 'algeria-states-wc'),
                __('Ben Daoud', 'algeria-states-wc'),
                __('Bir Kasdali', 'algeria-states-wc'),
                __('Bordj Ghedir', 'algeria-states-wc'),
                __('Bordj Zemmoura', 'algeria-states-wc'),
                __('Colla', 'algeria-states-wc'),
                __('Djaafra', 'algeria-states-wc'),
                __('El Achir', 'algeria-states-wc'),
                __('El Annasseur', 'algeria-states-wc'),
                __('El Euch', 'algeria-states-wc'),
                __('El Mhir', 'algeria-states-wc'),
                __('El Main', 'algeria-states-wc'),
                __('Elhammadia', 'algeria-states-wc'),
                __('Ghailasa', 'algeria-states-wc'),
                __('Haraza', 'algeria-states-wc'),
                __('Hasnaoua', 'algeria-states-wc'),
                __('Khelil', 'algeria-states-wc'),
                __('Ksour', 'algeria-states-wc'),
                __('Mansoura', 'algeria-states-wc'),
                __('Medjana', 'algeria-states-wc'),
                __('Ouled Brahem', 'algeria-states-wc'),
                __('Ouled Dahmane', 'algeria-states-wc'),
                __('Ouled Sidi-Brahim', 'algeria-states-wc'),
                __('Rabta', 'algeria-states-wc'),
                __('Ras El Oued', 'algeria-states-wc'),
                __('Sidi-Embarek', 'algeria-states-wc'),
                __('Taglait', 'algeria-states-wc'),
                __('Tassamert', 'algeria-states-wc'),
                __('Tefreg', 'algeria-states-wc'),
                __('Teniet En Nasr', 'algeria-states-wc'),
                __('Tixter', 'algeria-states-wc'),
            ),
            '35' => array(
                __('Afir', 'algeria-states-wc'),
                __('Ammal', 'algeria-states-wc'),
                __('Baghlia', 'algeria-states-wc'),
                __('Ben Choud', 'algeria-states-wc'),
                __('Beni Amrane', 'algeria-states-wc'),
                __('Bordj Menaiel', 'algeria-states-wc'),
                __('Boudouaou', 'algeria-states-wc'),
                __('Boudouaou El Bahri', 'algeria-states-wc'),
                __('Boumerdes', 'algeria-states-wc'),
                __('Bouzegza Keddara', 'algeria-states-wc'),
                __('Chabet El Ameur', 'algeria-states-wc'),
                __('Corso', 'algeria-states-wc'),
                __('Dellys', 'algeria-states-wc'),
                __('Djinet', 'algeria-states-wc'),
                __('El Kharrouba', 'algeria-states-wc'),
                __('Hammedi', 'algeria-states-wc'),
                __('Isser', 'algeria-states-wc'),
                __('Khemis El Khechna', 'algeria-states-wc'),
                __('Larbatache', 'algeria-states-wc'),
                __('Leghata', 'algeria-states-wc'),
                __('Naciria', 'algeria-states-wc'),
                __('Ouled Aissa', 'algeria-states-wc'),
                __('Ouled Hedadj', 'algeria-states-wc'),
                __('Ouled Moussa', 'algeria-states-wc'),
                __('Si Mustapha', 'algeria-states-wc'),
                __('Sidi Daoud', 'algeria-states-wc'),
                __('Souk El Had', 'algeria-states-wc'),
                __('Taourga', 'algeria-states-wc'),
                __('Thenia', 'algeria-states-wc'),
                __('Tidjelabine', 'algeria-states-wc'),
                __('Timezrit', 'algeria-states-wc'),
                __('Zemmouri', 'algeria-states-wc'),
            ),
            '36' => array(
                __('Ain El Assel', 'algeria-states-wc'),
                __('Ain Kerma', 'algeria-states-wc'),
                __('Asfour', 'algeria-states-wc'),
                __('Ben M Hidi', 'algeria-states-wc'),
                __('Berrihane', 'algeria-states-wc'),
                __('Besbes', 'algeria-states-wc'),
                __('Bougous', 'algeria-states-wc'),
                __('Bouhadjar', 'algeria-states-wc'),
                __('Bouteldja', 'algeria-states-wc'),
                __('Chebaita Mokhtar', 'algeria-states-wc'),
                __('Chefia', 'algeria-states-wc'),
                __('Chihani', 'algeria-states-wc'),
                __('Drean', 'algeria-states-wc'),
                __('Echatt', 'algeria-states-wc'),
                __('El Aioun', 'algeria-states-wc'),
                __('El Kala', 'algeria-states-wc'),
                __('El Tarf', 'algeria-states-wc'),
                __('Hammam Beni Salah', 'algeria-states-wc'),
                __('Lac Des Oiseaux', 'algeria-states-wc'),
                __('Oued Zitoun', 'algeria-states-wc'),
                __('Raml Souk', 'algeria-states-wc'),
                __('Souarekh', 'algeria-states-wc'),
                __('Zerizer', 'algeria-states-wc'),
                __('Zitouna', 'algeria-states-wc'),
            ),
            '37' => array(
                __('Oum El Assel', 'algeria-states-wc'),
                __('Tindouf', 'algeria-states-wc'),
            ),
            '38' => array(
                __('Ammari', 'algeria-states-wc'),
                __('Beni Chaib', 'algeria-states-wc'),
                __('Beni Lahcene', 'algeria-states-wc'),
                __('Bordj Bounaama', 'algeria-states-wc'),
                __('Bordj El Emir Abdelkader', 'algeria-states-wc'),
                __('Boucaid', 'algeria-states-wc'),
                __('Khemisti', 'algeria-states-wc'),
                __('Larbaa', 'algeria-states-wc'),
                __('Lardjem', 'algeria-states-wc'),
                __('Layoune', 'algeria-states-wc'),
                __('Lazharia', 'algeria-states-wc'),
                __('Maacem', 'algeria-states-wc'),
                __('Melaab', 'algeria-states-wc'),
                __('Ouled Bessam', 'algeria-states-wc'),
                __('Sidi Abed', 'algeria-states-wc'),
                __('Sidi Boutouchent', 'algeria-states-wc'),
                __('Sidi Lantri', 'algeria-states-wc'),
                __('Sidi Slimane', 'algeria-states-wc'),
                __('Tamellahet', 'algeria-states-wc'),
                __('Theniet El Had', 'algeria-states-wc'),
                __('Tissemsilt', 'algeria-states-wc'),
                __('Youssoufia', 'algeria-states-wc'),
            ),
            '39' => array(
                __('Bayadha', 'algeria-states-wc'),
                __('Ben Guecha', 'algeria-states-wc'),
                __('Debila', 'algeria-states-wc'),
                __('Douar El Maa', 'algeria-states-wc'),
                __('El Ogla', 'algeria-states-wc'),
                __('El-Oued', 'algeria-states-wc'),
                __('Guemar', 'algeria-states-wc'),
                __('Hamraia', 'algeria-states-wc'),
                __('Hassani Abdelkrim', 'algeria-states-wc'),
                __('Hassi Khalifa', 'algeria-states-wc'),
                __('Kouinine', 'algeria-states-wc'),
                __('Magrane', 'algeria-states-wc'),
                __('Mih Ouansa', 'algeria-states-wc'),
                __('Nakhla', 'algeria-states-wc'),
                __('Oued El Alenda', 'algeria-states-wc'),
                __('Ourmes', 'algeria-states-wc'),
                __('Reguiba', 'algeria-states-wc'),
                __('Robbah', 'algeria-states-wc'),
                __('Sidi Aoun', 'algeria-states-wc'),
                __('Taghzout', 'algeria-states-wc'),
                __('Taleb Larbi', 'algeria-states-wc'),
                __('Trifaoui', 'algeria-states-wc'),
            ),
            '40' => array(
                __('Ain Touila', 'algeria-states-wc'),
                __('Babar', 'algeria-states-wc'),
                __('Baghai', 'algeria-states-wc'),
                __('Bouhmama', 'algeria-states-wc'),
                __('Chechar', 'algeria-states-wc'),
                __('Chelia', 'algeria-states-wc'),
                __('Djellal', 'algeria-states-wc'),
                __('El Hamma', 'algeria-states-wc'),
                __('El Mahmal', 'algeria-states-wc'),
                __('El Oueldja', 'algeria-states-wc'),
                __('Ensigha', 'algeria-states-wc'),
                __('Kais', 'algeria-states-wc'),
                __('Khenchela', 'algeria-states-wc'),
                __('Khirane', 'algeria-states-wc'),
                __('Msara', 'algeria-states-wc'),
                __('Mtoussa', 'algeria-states-wc'),
                __('Ouled Rechache', 'algeria-states-wc'),
                __('Remila', 'algeria-states-wc'),
                __('Tamza', 'algeria-states-wc'),
                __('Taouzianat', 'algeria-states-wc'),
                __('Yabous', 'algeria-states-wc'),
            ),
            '41' => array(
                __('Ain Soltane', 'algeria-states-wc'),
                __('Ain Zana', 'algeria-states-wc'),
                __('Bir Bouhouche', 'algeria-states-wc'),
                __('Drea', 'algeria-states-wc'),
                __('Haddada', 'algeria-states-wc'),
                __('Hanencha', 'algeria-states-wc'),
                __('Khedara', 'algeria-states-wc'),
                __('Khemissa', 'algeria-states-wc'),
                __('Mdaourouche', 'algeria-states-wc'),
                __('Machroha', 'algeria-states-wc'),
                __('Merahna', 'algeria-states-wc'),
                __('Oued Kebrit', 'algeria-states-wc'),
                __('Ouillen', 'algeria-states-wc'),
                __('Ouled Driss', 'algeria-states-wc'),
                __('Ouled Moumen', 'algeria-states-wc'),
                __('Oum El Adhaim', 'algeria-states-wc'),
                __('Ragouba', 'algeria-states-wc'),
                __('Safel El Ouiden', 'algeria-states-wc'),
                __('Sedrata', 'algeria-states-wc'),
                __('Sidi Fredj', 'algeria-states-wc'),
                __('Souk Ahras', 'algeria-states-wc'),
                __('Taoura', 'algeria-states-wc'),
                __('Terraguelt', 'algeria-states-wc'),
                __('Tiffech', 'algeria-states-wc'),
                __('Zaarouria', 'algeria-states-wc'),
                __('Zouabi', 'algeria-states-wc'),
            ),
            '42' => array(
                __('Aghbal', 'algeria-states-wc'),
                __('Ahmer El Ain', 'algeria-states-wc'),
                __('Ain Tagourait', 'algeria-states-wc'),
                __('Attatba', 'algeria-states-wc'),
                __('Beni Mileuk', 'algeria-states-wc'),
                __('Bou Haroun', 'algeria-states-wc'),
                __('Bou Ismail', 'algeria-states-wc'),
                __('Bourkika', 'algeria-states-wc'),
                __('Chaiba', 'algeria-states-wc'),
                __('Cherchell', 'algeria-states-wc'),
                __('Damous', 'algeria-states-wc'),
                __('Douaouda', 'algeria-states-wc'),
                __('Fouka', 'algeria-states-wc'),
                __('Gouraya', 'algeria-states-wc'),
                __('Hadjout', 'algeria-states-wc'),
                __('Hadjret Ennous', 'algeria-states-wc'),
                __('Khemisti', 'algeria-states-wc'),
                __('Kolea', 'algeria-states-wc'),
                __('Larhat', 'algeria-states-wc'),
                __('Menaceur', 'algeria-states-wc'),
                __('Merad', 'algeria-states-wc'),
                __('Messelmoun', 'algeria-states-wc'),
                __('Nador', 'algeria-states-wc'),
                __('Sidi Ghiles', 'algeria-states-wc'),
                __('Sidi Rached', 'algeria-states-wc'),
                __('Sidi Semiane', 'algeria-states-wc'),
                __('Sidi-Amar', 'algeria-states-wc'),
                __('Tipaza', 'algeria-states-wc'),
            ),
            '43' => array(
                __('Ahmed Rachedi', 'algeria-states-wc'),
                __('Ain Beida Harriche', 'algeria-states-wc'),
                __('Ain Mellouk', 'algeria-states-wc'),
                __('Ain Tine', 'algeria-states-wc'),
                __('Amira Arres', 'algeria-states-wc'),
                __('Benyahia Abderrahmane', 'algeria-states-wc'),
                __('Bouhatem', 'algeria-states-wc'),
                __('Chelghoum Laid', 'algeria-states-wc'),
                __('Chigara', 'algeria-states-wc'),
                __('Derrahi Bousselah', 'algeria-states-wc'),
                __('El Ayadi Barbes', 'algeria-states-wc'),
                __('El Mechira', 'algeria-states-wc'),
                __('Ferdjioua', 'algeria-states-wc'),
                __('Grarem Gouga', 'algeria-states-wc'),
                __('Hamala', 'algeria-states-wc'),
                __('Mila', 'algeria-states-wc'),
                __('Minar Zarza', 'algeria-states-wc'),
                __('Oued Athmenia', 'algeria-states-wc'),
                __('Oued Endja', 'algeria-states-wc'),
                __('Oued Seguen', 'algeria-states-wc'),
                __('Ouled Khalouf', 'algeria-states-wc'),
                __('Rouached', 'algeria-states-wc'),
                __('Sidi Khelifa', 'algeria-states-wc'),
                __('Sidi Merouane', 'algeria-states-wc'),
                __('Tadjenanet', 'algeria-states-wc'),
                __('Tassadane Haddada', 'algeria-states-wc'),
                __('Tassala Lematai', 'algeria-states-wc'),
                __('Teleghma', 'algeria-states-wc'),
                __('Terrai Bainen', 'algeria-states-wc'),
                __('Tiberguent', 'algeria-states-wc'),
                __('Yahia Beniguecha', 'algeria-states-wc'),
                __('Zeghaia', 'algeria-states-wc'),
            ),
            '44' => array(
                __('Ain-Benian', 'algeria-states-wc'),
                __('Ain-Bouyahia', 'algeria-states-wc'),
                __('Ain-Defla', 'algeria-states-wc'),
                __('Ain-Lechiakh', 'algeria-states-wc'),
                __('Ain-Soltane', 'algeria-states-wc'),
                __('Ain-Torki', 'algeria-states-wc'),
                __('Arib', 'algeria-states-wc'),
                __('Bathia', 'algeria-states-wc'),
                __('Belaas', 'algeria-states-wc'),
                __('Ben Allal', 'algeria-states-wc'),
                __('Bir-Ould-Khelifa', 'algeria-states-wc'),
                __('Birbouche', 'algeria-states-wc'),
                __('Bordj-Emir-Khaled', 'algeria-states-wc'),
                __('Boumedfaa', 'algeria-states-wc'),
                __('Bourached', 'algeria-states-wc'),
                __('Djelida', 'algeria-states-wc'),
                __('Djemaa Ouled Cheikh', 'algeria-states-wc'),
                __('Djendel', 'algeria-states-wc'),
                __('El-Abadia', 'algeria-states-wc'),
                __('El-Amra', 'algeria-states-wc'),
                __('El-Attaf', 'algeria-states-wc'),
                __('El-Maine', 'algeria-states-wc'),
                __('Hammam-Righa', 'algeria-states-wc'),
                __('Hassania', 'algeria-states-wc'),
                __('Hoceinia', 'algeria-states-wc'),
                __('Khemis-Miliana', 'algeria-states-wc'),
                __('Mekhatria', 'algeria-states-wc'),
                __('Miliana', 'algeria-states-wc'),
                __('Oued Chorfa', 'algeria-states-wc'),
                __('Oued Djemaa', 'algeria-states-wc'),
                __('Rouina', 'algeria-states-wc'),
                __('Sidi-Lakhdar', 'algeria-states-wc'),
                __('Tacheta Zegagha', 'algeria-states-wc'),
                __('Tarik-Ibn-Ziad', 'algeria-states-wc'),
                __('Tiberkanine', 'algeria-states-wc'),
                __('Zeddine', 'algeria-states-wc'),
            ),
            '45' => array(
                __('Ain Ben Khelil', 'algeria-states-wc'),
                __('Ain Sefra', 'algeria-states-wc'),
                __('Asla', 'algeria-states-wc'),
                __('Djenienne Bourezg', 'algeria-states-wc'),
                __('El Biodh', 'algeria-states-wc'),
                __('Kasdir', 'algeria-states-wc'),
                __('Makmen Ben Amar', 'algeria-states-wc'),
                __('Mecheria', 'algeria-states-wc'),
                __('Moghrar', 'algeria-states-wc'),
                __('Naama', 'algeria-states-wc'),
                __('Sfissifa', 'algeria-states-wc'),
                __('Tiout', 'algeria-states-wc'),
            ),
            '46' => array(
                __('Aghlal', 'algeria-states-wc'),
                __('Ain El Arbaa', 'algeria-states-wc'),
                __('Ain Kihal', 'algeria-states-wc'),
                __('Ain Temouchent', 'algeria-states-wc'),
                __('Ain Tolba', 'algeria-states-wc'),
                __('Aoubellil', 'algeria-states-wc'),
                __('Beni Saf', 'algeria-states-wc'),
                __('Bouzedjar', 'algeria-states-wc'),
                __('Chaabat El Ham', 'algeria-states-wc'),
                __('Chentouf', 'algeria-states-wc'),
                __('El Amria', 'algeria-states-wc'),
                __('El Maleh', 'algeria-states-wc'),
                __('El Messaid', 'algeria-states-wc'),
                __('Emir Abdelkader', 'algeria-states-wc'),
                __('Hammam Bou Hadjar', 'algeria-states-wc'),
                __('Hassasna', 'algeria-states-wc'),
                __('Hassi El Ghella', 'algeria-states-wc'),
                __('Oued Berkeche', 'algeria-states-wc'),
                __('Oued Sebbah', 'algeria-states-wc'),
                __('Ouled Boudjemaa', 'algeria-states-wc'),
                __('Ouled Kihal', 'algeria-states-wc'),
                __('Oulhaca El Gheraba', 'algeria-states-wc'),
                __('Sidi Ben Adda', 'algeria-states-wc'),
                __('Sidi Boumediene', 'algeria-states-wc'),
                __('Sidi Ouriache', 'algeria-states-wc'),
                __('Sidi Safi', 'algeria-states-wc'),
                __('Tamzoura', 'algeria-states-wc'),
                __('Terga', 'algeria-states-wc'),
            ),
            '47' => array(
                __('Berriane', 'algeria-states-wc'),
                __('Bounoura', 'algeria-states-wc'),
                __('Dhayet Bendhahoua', 'algeria-states-wc'),
                __('El Atteuf', 'algeria-states-wc'),
                __('El Guerrara', 'algeria-states-wc'),
                __('Ghardaia', 'algeria-states-wc'),
                __('Mansoura', 'algeria-states-wc'),
                __('Metlili', 'algeria-states-wc'),
                __('Sebseb', 'algeria-states-wc'),
                __('Zelfana', 'algeria-states-wc'),
            ),
            '48' => array(
                __('Ain Rahma', 'algeria-states-wc'),
                __('Ain-Tarek', 'algeria-states-wc'),
                __('Ammi Moussa', 'algeria-states-wc'),
                __('Belaassel Bouzagza', 'algeria-states-wc'),
                __('Bendaoud', 'algeria-states-wc'),
                __('Beni Dergoun', 'algeria-states-wc'),
                __('Beni Zentis', 'algeria-states-wc'),
                __('Dar Ben Abdelah', 'algeria-states-wc'),
                __('Djidiouia', 'algeria-states-wc'),
                __('El Hmadna', 'algeria-states-wc'),
                __('El Hassi', 'algeria-states-wc'),
                __('El Ouldja', 'algeria-states-wc'),
                __('El-Guettar', 'algeria-states-wc'),
                __('El-Matmar', 'algeria-states-wc'),
                __('Had Echkalla', 'algeria-states-wc'),
                __('Hamri', 'algeria-states-wc'),
                __('Kalaa', 'algeria-states-wc'),
                __('Lahlef', 'algeria-states-wc'),
                __('Mazouna', 'algeria-states-wc'),
                __('Mediouna', 'algeria-states-wc'),
                __('Mendes', 'algeria-states-wc'),
                __('Merdja Sidi Abed', 'algeria-states-wc'),
                __('Ouarizane', 'algeria-states-wc'),
                __('Oued El Djemaa', 'algeria-states-wc'),
                __('Oued Essalem', 'algeria-states-wc'),
                __('Oued-Rhiou', 'algeria-states-wc'),
                __('Ouled Aiche', 'algeria-states-wc'),
                __('Ouled Sidi Mihoub', 'algeria-states-wc'),
                __('Ramka', 'algeria-states-wc'),
                __('Relizane', 'algeria-states-wc'),
                __('Sidi Khettab', 'algeria-states-wc'),
                __('Sidi Lazreg', 'algeria-states-wc'),
                __('Sidi Mhamed Benali', 'algeria-states-wc'),
                __('Sidi Mhamed Benaouda', 'algeria-states-wc'),
                __('Sidi Saada', 'algeria-states-wc'),
                __('Souk El Had', 'algeria-states-wc'),
                __('Yellel', 'algeria-states-wc'),
                __('Zemmoura', 'algeria-states-wc'),
            ),
            '49' => array(
                __('Aougrout', 'algeria-states-wc'),
                __('Charouine', 'algeria-states-wc'),
                __('Deldoul', 'algeria-states-wc'),
                __('Ksar Kaddour', 'algeria-states-wc'),
                __('Metarfa', 'algeria-states-wc'),
                __('Ouled Aissa', 'algeria-states-wc'),
                __('Ouled Said', 'algeria-states-wc'),
                __('Talmine', 'algeria-states-wc'),
                __('Timimoun', 'algeria-states-wc'),
                __('Tinerkouk', 'algeria-states-wc'),
            ),
            '50' => array(
                __('Bordj Badji Mokhtar', 'algeria-states-wc'),
                __('Timiaouine', 'algeria-states-wc'),
            ),
            '51' => array(
                __('Besbes', 'algeria-states-wc'),
                __('Chaiba', 'algeria-states-wc'),
                __('Doucen', 'algeria-states-wc'),
                __('Ouled Djellal', 'algeria-states-wc'),
                __('Ras El Miad', 'algeria-states-wc'),
                __('Sidi Khaled', 'algeria-states-wc'),
            ),
            '52' => array(
                __('Beni-Abbes', 'algeria-states-wc'),
                __('Beni-Ikhlef', 'algeria-states-wc'),
                __('El Ouata', 'algeria-states-wc'),
                __('Igli', 'algeria-states-wc'),
                __('Kerzaz', 'algeria-states-wc'),
                __('Ksabi', 'algeria-states-wc'),
                __('Ouled-Khodeir', 'algeria-states-wc'),
                __('Tamtert', 'algeria-states-wc'),
                __('Timoudi', 'algeria-states-wc'),
            ),
            '53' => array(
                __('Ain Salah', 'algeria-states-wc'),
                __('Foggaret Ezzoua', 'algeria-states-wc'),
                __('Inghar', 'algeria-states-wc'),
            ),
            '54' => array(
                __('Ain Guezzam', 'algeria-states-wc'),
                __('Tin Zouatine', 'algeria-states-wc'),
            ),
            '55' => array(
                __('Benaceur', 'algeria-states-wc'),
                __('Blidet Amor', 'algeria-states-wc'),
                __('El Alia', 'algeria-states-wc'),
                __('El-Hadjira', 'algeria-states-wc'),
                __('Mnaguer', 'algeria-states-wc'),
                __('Megarine', 'algeria-states-wc'),
                __('Nezla', 'algeria-states-wc'),
                __('Sidi Slimane', 'algeria-states-wc'),
                __('Taibet', 'algeria-states-wc'),
                __('Tebesbest', 'algeria-states-wc'),
                __('Temacine', 'algeria-states-wc'),
                __('Touggourt', 'algeria-states-wc'),
                __('Zaouia El Abidia', 'algeria-states-wc'),
            ),
            '56' => array(
                __('Bordj El Haouass', 'algeria-states-wc'),
                __('Djanet', 'algeria-states-wc'),
            ),
            '57' => array(
                __('Djamaa', 'algeria-states-wc'),
                __('El Meghaier', 'algeria-states-wc'),
                __('Mrara', 'algeria-states-wc'),
                __('Oum Touyour', 'algeria-states-wc'),
                __('Sidi Amrane', 'algeria-states-wc'),
                __('Sidi Khelil', 'algeria-states-wc'),
                __('Still', 'algeria-states-wc'),
                __('Tenedla', 'algeria-states-wc'),
            ),
            '58' => array(
                __('El Meniaa', 'algeria-states-wc'),
                __('Hassi Fehal', 'algeria-states-wc'),
                __('Hassi Gara', 'algeria-states-wc'),
            )
        );
        return isset($all_cities[$wilaya_id]) ? $all_cities[$wilaya_id] : array();
    }
}